import { ProductHighlightProp } from '../components/product/ProductHighlight'
import { CategoryNavProps } from '../components/category/CategoryNav'
import { CategoryPopoverProps } from '../components/category/CategoryPopover'
import { SideBarProps } from 'src/components/Sidebar/SideBar'

export const CONSTANT_CAT_LIST = [
	{
		category: 'asd',
		details: [
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
		],
	},
	{
		category: 'asd',
		details: [
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
		],
	},
	{
		category: 'asd',
		details: [
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
		],
	},
	{
		category: 'asd',
		details: [
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
			[
				{
					header: 'GİYİM',
					list: [
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
						{ text: 'Tişört', url: 'tişört' },
						{ text: 'Şort', url: 'sort' },
					],
				},
				{
					header: 'AYAKKABI',
					list: [
						{ text: 'Spor', url: 'spor' },
						{ text: 'Günlük', url: 'günlük' },
						{ text: 'Yürüyüş', url: 'yürüyüş' },
						{ text: 'terlik', url: 'terlik' },
						{ text: 'Klasik', url: 'klasik' },
						{ text: 'Bot', url: 'bot' },
						{ text: 'Tişört', url: 'tişört' },
					],
				},
			],
		],
	},
]

export const PRODUCT_HL: ProductHighlightProp['data'] = {
	image: '/product.webp',
	brand: 'Adidas',
	model: 'aditru',
	class: ' Gri Outdoor Ayakkabı',
	link: '',
	rating: 4,
	rateCount: 1241,
	standartPrice: 891,
	discountedPrice: 682,
	extraExp: 'Son 30 günün en düşük fiyatı',
	isStary: false,
	isMostSelling: true,
}

export const ALL_PRODUCTS: ProductHighlightProp['data'][] = [
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
	{
		image: '/product.webp',
		brand: 'Adidas',
		model: 'aditru',
		class: ' Gri Outdoor Ayakkabı',
		link: '',
		rating: 4,
		rateCount: 1241,
		standartPrice: 891,
		discountedPrice: 682,
		extraExp: 'Son 30 günün en düşük fiyatı',
		isStary: false,
		isMostSelling: true,
	},
]

export const SIDEBAR_DATA: SideBarProps['data'] = [
	{
		title: 'İlgili Kategoriler',
		isCheckBox: false,
		data: [
			{
				label: 'Günlük',
				value: 1,
			},
			{
				label: 'Spor',
				value: 2,
			},
			{
				label: 'Koşu',
				value: 3,
			},
			{
				label: 'Basketbol',
				value: 4,
			},
			{
				label: 'Futbol',
				value: 5,
			},
			{
				label: 'Tenis',
				value: 6,
			},
			{
				label: 'Dağcılık',
				value: 7,
			},
			{
				label: 'Bisiklet',
				value: 8,
			},
			{
				label: 'Havuz',
				value: 9,
			},
			{
				label: 'Yürüyüş',
				value: 10,
			},
			{
				label: 'Tirmanış',
				value: 11,
			},
		],
	},
	{
		title: 'Markalar',
		isCheckBox: true,
		data: [
			{ label: 'Adidas', value: 1 },
			{ label: 'Nike', value: 2 },
			{ label: 'Puma', value: 3 },
			{ label: 'New Balance', value: 4 },
			{ label: 'Sketchers', value: 5 },
			{ label: 'Jump', value: 6 },
			{ label: 'Kemal Tanca', value: 7 },
			{ label: 'FreshUp', value: 8 },
			{ label: 'Kiğılı', value: 9 },
			{ label: 'Lumberjack', value: 10 },
			{ label: 'Kinetix', value: 11 },
			{ label: 'Hummel', value: 12 },
			{ label: 'Reebok', value: 13 },
		],
	},
	{
		title: 'Cinsiyet',
		isCheckBox: true,
		data: [
			{ label: 'Erkek', value: 412 },
			{ label: 'Kadın', value: 123 },
		],
	},

	{
		title: 'Beden',
		isCheckBox: true,
		data: [
			{ label: 'XXS', value: 12341243 },
			{ label: 'XS', value: 41212412 },
			{ label: 'S', value: 1231242412 },
			{ label: 'M', value: 1231412412 },
			{ label: 'L', value: 123141234512 },
			{ label: 'XL', value: 12351234 },
			{ label: 'XXL', value: 12321455 },
		],
	},
	{
		title: 'Fiyat',
		isCheckBox: true,
		data: [
			{ label: '0-500', value: 12341569243 },
			{ label: '500-1000', value: 412152412 },
			{ label: '1000-1500', value: 1236912412 },
			{ label: '1500-2000', value: 123694112412 },
			{ label: '2000-3000', value: 123457124534512 },
			{ label: '3000-4000', value: 1232251234 },
			{ label: '4000+', value: 123251251455 },
		],
	},
	{
		title: 'Renk',
		isCheckBox: true,
		data: [
			{ label: 'Kırmızı', value: 12341512243 },
			{ label: 'Sarı', value: 412121512412 },
			{ label: 'Mavi', value: 12315122412 },
			{ label: 'Yeşil', value: 12312455112 },
			{ label: 'Turuncu', value: 12321232314512 },
			{ label: 'Turkuaz', value: 1452351234 },
			{ label: 'Siyah', value: 123215455 },
			{ label: 'Beyaz', value: 111252321455 },
		],
	},
]
