export const BRANDBOX_CONSTANTS = [
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
	{ name: 'Karaca', src: '/karaca.webp' },
]
